#!/bin/bash
set -o pipefail

<<screensht

 _____ _____ _____ _____ _____ _____ _____ _____ _____
|   __|     | __  |   __|   __|   | |   __|  |  |_   _|
|__   |   --|    -|   __|   __| | | |__   |     | | |
|_____|_____|__|__|_____|_____|_|___|_____|__|__| |_|
Simple Script To Take Aesthetic Screenshots!
using maim, imagemagick, colord and AwesomeWM API

@author rxyhn
https://github.com/rxyhn

Modified by yxwang
Make this a pure screen shot program without prettifier

screensht

# =============================================

# Directory
_SCREENSHOT_DIR_=$HOME/Pictures/Screenshots
_LOG_FILE_="$_SCREENSHOT_DIR_/.screensht.log"

# =============================================

function check() {
    if [[ $? -eq 1 && ${PIPESTATUS[0]} -eq 1 ]]; then
        _end_job_=$(date +%s)
        summary $_start_job_ $_end_job_ 'failed' && notify-send -u critical -t 3000 -a "Screenshot Tool" "Screensht!" "screenshot aborted" >> $_LOG_FILE_ 2>&1
        exit 1
    fi
}

# Check save directory
# Create it if it doesn't exist
function check_dir() {
	if [[ ! -d "$_SCREENSHOT_DIR_" ]]; then
		mkdir -p "$_SCREENSHOT_DIR_"
	fi
}

function get_latest_img() { 
    _LATEST_IMAGE_=$(/bin/ls -th $_SCREENSHOT_DIR_ | grep -vE '.screensht.png$' | grep -E '.png$' | head -n 1)

    if [[ $( echo "$_LATEST_IMAGE_" | wc -w ) -eq 0 ]]; then
        exit 1
    else
        _LATEST_IMAGE_="$_SCREENSHOT_DIR_/$_LATEST_IMAGE_"
    fi
}


function summary() {
    _runtime_job_=$(($2-$1))
    hours=$((_runtime_job_ / 3600)); minutes=$(( (_runtime_job_ % 3600) / 60 )); seconds=$(( (_runtime_job_ % 3600) % 60 ))

    if [[ $3 != "failed" ]]; then
        xclip -selection clipboard -t image/png -i $_target_file_ >> $_LOG_FILE_ 2>&1

        awesome-client "
	    -- IMPORTANT NOTE: THIS PART OF THE SCRIPT IS LUA!
	    naughty = require('naughty')
	    awful = require('awful')
	    beautiful = require('beautiful')
	    dpi = beautiful.xresources.apply_dpi

	    local open_image = naughty.action {
	    	name = 'Open',
	       	icon_only = false,
	    }

	    local delete_image = naughty.action {
	    	name = 'Delete',
	       	icon_only = false,
	    }

	    -- Execute the callback when 'Open' is pressed
	    open_image:connect_signal('invoked', function()
	    	awful.spawn('xdg-open ' .. '${_target_file_}', false)
	    end)

	    -- Execute the callback when 'Delete' is pressed
	    delete_image:connect_signal('invoked', function()
	    	awful.spawn('gio trash ' .. '${_target_file_}', false)
	    end)

	    -- Show notification
	    naughty.notification ({
	    	app_name = 'Screenshot Tool',
	    	icon = '${_target_file_}',
	    	timeout = 10,
	    	title = 'Screensht!',
	    	message = '${_notif_message_}',
	    	actions = { open_image, delete_image }
	    })
	    "
    fi
}

function main() {
    check_dir

    rm -f $_LOG_FILE_
    _start_job_=$(date +%s)

	_screenshot_command_="$1"
	_notif_message_="$2"

    $_screenshot_command_ $_SCREENSHOT_DIR_\/$_start_job_.png> /dev/null 2>&1
    check

    get_latest_img
    
    _end_job_=$(date +%s)
    summary $_start_job_ $_end_job_
}

# Check the args passed
if [ -z "$1" ] || ([ "$1" != 'full' ] && [ "$1" != 'area' ]);
then
	echo "
	Requires an argument:
	area 	- Area screenshot
	full 	- Fullscreen screenshot

	Example:
	./screensht area
	./screensht full
	"
elif [ "$1" = 'full' ];
then
	msg="Full screenshot saved and copied to clipboard!"
	main 'maim -u -m 10' "${msg}"
elif [ "$1" = 'area' ];
then
	msg='Area screenshot saved and copied to clipboard!'
	main 'maim -u -m 10 -s -b 2 -c 0.35,0.55,0.85,0.25 -l' "${msg}"
fi
